import { corsHeaders } from "../_shared/cors.ts";

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) throw new Error("Missing authorization header");

    const { createClient } = await import("https://esm.sh/@supabase/supabase-js@2");

    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_ANON_KEY")!
    );
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser(authHeader.replace("Bearer ", ""));
    if (authError || !user) throw new Error("Unauthorized");

    const { to, resident_name, faculty_name, date_start, date_end, pdf_base64 } =
      await req.json();

    if (!to || !pdf_base64) throw new Error("Missing required fields");

    const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");
    if (!RESEND_API_KEY) throw new Error("RESEND_API_KEY is not configured");

    const fromEmail = Deno.env.get("RESEND_FROM_EMAIL") || "noreply@resend.dev";
    const filename = `milestone-report-${resident_name
      .replace(/\s+/g, "-")
      .toLowerCase()}-${date_start}-to-${date_end}.pdf`;

    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${RESEND_API_KEY}`,
      },
      body: JSON.stringify({
        from: fromEmail,
        to: [to],
        subject: `Milestone Report: ${resident_name} (${date_start} to ${date_end})`,
        html: `<p>Please find attached the milestone assessment report for <strong>${resident_name}</strong>, covering the period ${date_start} to ${date_end}.</p><p>Generated by ${faculty_name} on ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}.</p><p style="color:#999;font-size:12px">— FM Tasks</p>`,
        attachments: [
          {
            filename,
            content: pdf_base64,
          },
        ],
      }),
    });

    if (!res.ok) {
      const errText = await res.text();
      throw new Error(`Resend error: ${res.status} ${errText}`);
    }

    const result = await res.json();

    return new Response(JSON.stringify({ success: true, id: result.id }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (err) {
    const error = err as Error;
    console.error("send-milestone-report error:", error.message);
    return new Response(JSON.stringify({ error: error.message }), {
      status: 400,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
